# Generated by Django 4.1.5 on 2023-01-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='logoManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='img/')),
            ],
            options={
                'verbose_name_plural': 'Logo Manager',
            },
        ),
    ]
